-- 1. STUDENT테이블에서 키가 큰 상위 5명 출력(중복고려 X, ROWNUM 사용)

SELECT *
FROM (
    SELECT S.*
    FROM STUDENT S
    WHERE STU_HEIGHT IS NOT NULL
    ORDER BY STU_HEIGHT DESC
) WHERE ROWNUM <= 5;
-- 2. STUDENT테이블에서 키가 큰 상위 5명 출력(RANK 사용)

SELECT *
FROM (
    SELECT 
        STU_NO, STU_NAME, STU_HEIGHT,
        RANK() OVER(ORDER BY STU_HEIGHT DESC) AS RANK
    FROM STUDENT
    WHERE STU_HEIGHT IS NOT NULL
) WHERE RANK <= 5;



