-- VIEW, PL/SQL(사용자 정의함수, TRIGGER, 프로시저 ..)

-- VIEW
SELECT * FROM EMP;

DROP VIEW EMP_VIEW;

CREATE OR REPLACE VIEW EMP_VIEW AS
SELECT EMPNO, ENAME, JOB, DNAME, LOC
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WITH READ ONLY -- 읽기전용
;

SELECT * FROM EMP_VIEW;

UPDATE EMP_VIEW SET
    ENAME = 'ZZZ';

SELECT * FROM EMP;
ROLLBACK;

-- VIEW에서 수정이 가능한 경우 (밑에 4개 다 만족해야 함)
-- 1. 읽기 전용 옵션 없을 때(WITH READ ONLY 없을 때)
-- 2. 조인이 없을 때
-- 3. GROUP 함수 없을 때
-- 4. DISTINCT 없을 때
-- # VIEW는 웬만하면 READ ONLY옵션 적용하는게 좋다.

SELECT 
    DISTINCT STU_NO, ENR_GRADE
FROM ENROL ;

-- 학번, 이름, 학과, 시험평균 점수를 출력하는 VIEW 생성. 읽기 전용으로
-- SCORE_VIEW

CREATE OR REPLACE VIEW SCORE_VIEW AS
SELECT S.STU_NO, STU_NAME, STU_DEPT, AVG(ENR_GRADE) AS AVG_SCORE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME, STU_DEPT
WITH READ ONLY
;

SELECT *
FROM SCORE_VIEW;
