-- 트리거
-- 특정(선택) 테이블에 변화가 생겼을 때(DELETE, INSERT, UPDATE)
-- 실행되는 프로시저

-- 샘플 트리거 생성

CREATE OR REPLACE TRIGGER TEMP_TRIGGER
    BEFORE -- 트리거 실행 시점(AFTER OR BEFORE)
    INSERT OR UPDATE ON STUDENT -- STUDENT 테이블이 INSERT 혹은 UPDATE가 발생했을 때 실행
    FOR EACH ROW -- 각 행별로 트리거 실행
                -- EX) UPDATE로 3명의 정보가 변경되면 트리거도 3번 실행
BEGIN
    DBMS_OUTPUT.PUT_LINE('변경 전 : ' || :OLD.STU_HEIGHT);
    DBMS_OUTPUT.PUT_LINE('변경 후 : ' || :NEW.STU_HEIGHT);
END;
/

UPDATE STUDENT SET
    STU_HEIGHT = STU_HEIGHT + 1
WHERE STU_NAME = '옥한빛';

CREATE TABLE EMP_LOG(
    L_EMPNO NUMBER,
    O_SAL NUMBER,
    N_SAL NUMBER,
    O_COMM NUMBER,
    N_COMM NUMBER,
    L_ID VARCHAR2(50),
    EVENT VARCHAR2(50),
    L_TIME DATE
);

CREATE OR REPLACE TRIGGER EMP_TRIGGER
    BEFORE
    INSERT OR UPDATE OR DELETE ON EMP
    FOR EACH ROW
BEGIN
    
--    IF :NEW.COMM IS NULL OR :NEW.COMM < 0 THEN
--        :NEW.COMM := 0;
--    END IF;
    IF INSERTING THEN
        INSERT INTO EMP_LOG
        VALUES(:NEW.EMPNO, :NEW.SAL, :NEW.SAL, :NEW.COMM, :NEW.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'I', SYSDATE);
    ELSIF UPDATING THEN
        INSERT INTO EMP_LOG
        VALUES(:NEW.EMPNO, :OLD.SAL, :NEW.SAL, :OLD.COMM, :NEW.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'U', SYSDATE);
    ELSIF DELETING THEN
        RAISE_APPLICATION_ERROR(-20002, '사원 데이터는 삭제 불가!');
    END IF;
END;
/

SELECT * FROM EMP;
UPDATE EMP SET 
    SAL = SAL + 50
WHERE EMPNO = '7499';
COMMIT;
SELECT * FROM EMP_LOG;

SELECT * FROM EMP;

INSERT INTO EMP
VALUES(1234, 'HONG', 'SALESMAN', '7698', SYSDATE, 2000, 200, 20);
COMMIT;

DELETE FROM EMP WHERE EMPNO = 1234;



--조건 1. 테이블명은 ENROL_LOG
--       컬럼은 과목번호, 학생번호, 수정전시험점수, 수정후시험점수, 작업자ID, 작업종류, 작업날짜
CREATE TABLE ENROL_LOG(
    L_SUBNO CHAR(3),
    L_STUNO CHAR(8),
    O_ENRGRADE NUMBER,
    N_ENRGRADE NUMBER,
    L_ID VARCHAR2(20),
    EVENT CHAR(1),
    L_TIME DATE
);
--조건 2. INSERT할 경우 ENROL_LOG에 해당 내용 자동 저장
--       단, 시험점수가 0~100사이가 아니면 0으로 저장
--조건 3. UPDATE할 경우 ENROL_LOG에 해당 내용 자동 저장
--       단, 시험점수가 0~100사이가 아니면 에러를 띄운 후 종료
--조건 4. DELETE할 경우 에러를 띄운 후 종료
​
CREATE OR REPLACE TRIGGER ENROL_TRIGGER
    BEFORE
    INSERT OR DELETE OR UPDATE ON ENROL
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        IF :NEW.ENR_GRADE < 0 OR :NEW.ENR_GRADE > 100 THEN
            :NEW.ENR_GRADE := 0;
        END IF;
        INSERT INTO ENROL_LOG
        VALUES(:NEW.SUB_NO, :NEW.STU_NO, :NEW.ENR_GRADE, :NEW.ENR_GRADE, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'I', SYSDATE);
    ELSIF UPDATING THEN
        IF :NEW.ENR_GRADE < 0 OR :NEW.ENR_GRADE > 100 THEN
            RAISE_APPLICATION_ERROR(-20003, '0~100사이 입력하셈');
        END IF;
        INSERT INTO ENROL_LOG
        VALUES(:NEW.SUB_NO, :NEW.STU_NO, :OLD.ENR_GRADE, :NEW.ENR_GRADE, SYS_CONTEXT('USERENV', 'SESSION_USER'), 'U', SYSDATE);
    ELSIF DELETING THEN
        RAISE_APPLICATION_ERROR(-20004, '성적은 삭제 불가!');
    END IF;
END;
/

UPDATE ENROL SET
    ENR_GRADE = 105
WHERE STU_NO = '20152088';

SELECT * FROM ENROL_LOG;
INSERT INTO ENROL 
VALUES (123, 12341234, 80);
DELETE FROM ENROL WHERE SUB_NO = 123;



