-- ROWNUM

SELECT S.*, ROWNUM
FROM STUDENT S
WHERE ROWNUM <= 3;

-- ROWNUM 값이 먼저 반영되고 정렬이 되므로 뒤죽박죽 됨
SELECT S.*, ROWNUM
FROM STUDENT S
WHERE STU_HEIGHT IS NOT NULL
ORDER BY STU_HEIGHT DESC;

--
SELECT T.*, ROWNUM
FROM (
    SELECT S.*
    FROM STUDENT S
    WHERE STU_HEIGHT IS NOT NULL
    ORDER BY STU_HEIGHT DESC
) T
WHERE ROWNUM <= 3;
